services:
  - type: web
    name: memory-game
    runtime: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        headers:
          - key: Cache-Control
            value: public, max-age=0, must-revalidate
